apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-aws
spec:
  provider:
    aws:
      service: SecretsManager
      role: iam-role
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: "aws-credentials"
            key: "id"
          secretAccessKeySecretRef:
            name: "aws-credentials"
            key: "key"